---
# File: playbook.yml - evolve Vault locally for demo purpose
# ansible-playbook playbook.yml

- name: Evolve Vault for demo - normal user
  hosts: 127.0.0.1
  connection: local
  any_errors_fatal: true
  tasks:
  - name: Creates directory
    file:
      path: "{{ ansible_env.HOME }}/.config/pet"
      state: directory
  - name: Move Snippets to Pet config directory
    copy:
      remote_src: True
      src: /tmp/snippet.toml
      dest: "{{ ansible_env.HOME }}/.config/pet"

- name: Evolve Vault for Demo - root
  hosts: 127.0.0.1
  connection: local
  any_errors_fatal: true
  become: true
  become_user: root
  tasks:
  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
  - name: Download Pet, Simple command-line snippet manager, written in Go.
    get_url:
      url: https://github.com/knqyf263/pet/releases/download/v0.3.2/pet_0.3.2_linux_amd64.deb
      dest: /tmp/
  - name: Install Pet
    apt:
      deb: /tmp/pet_0.3.2_linux_amd64.deb
      state: present
