---
# File: playbook.yml - evolve Vault locally for demo purpose
# ansible-playbook playbook.yml

- name: Evolve Vault for Demo - root
  hosts: 127.0.0.1
  connection: local
  any_errors_fatal: true
  become: true
  become_user: root
  tasks:
  - name: Adds gcloud key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adds gcloud repos
    apt_repository:
      repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
      update_cache: yes

  - name: install required packages
    apt:
      pkg: ['zsh', 'nginx', 'jq', 'unzip', 'mysql-client', 'google-cloud-sdk', 'python-pip', 'python-setuptools', 'python-openssl', 'python-crcmod']
      state: latest

  - name: Download Pet, Simple command-line snippet manager, written in Go.
    get_url:
      url: https://github.com/knqyf263/pet/releases/download/v0.3.2/pet_0.3.2_linux_amd64.deb
      dest: /tmp/

  - name: Install Pet
    apt:
      deb: /tmp/pet_0.3.2_linux_amd64.deb
      state: present

  - name: Consul-template download
    get_url:
      url: https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.zip
      dest: /tmp/

  - name: Consul-template installation
    unarchive:
      src: /tmp/consul-template_0.19.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Consul-template related directories
    file:
      path: "{{item}}"
      state: directory
    with_items: ["/etc/consul-template.d/", "/etc/nginx/certs/"]

  - name: Consult-template configuration and templates
    copy:
      src: "{{item.key}}"
      dest: "{{item.value}}"
    with_dict: {"/tmp/pki-demo.hcl": "/etc/consul-template.d/pki-demo.hcl", "/tmp/cert.tpl": "/etc/consul-template.d/cert.tpl", "/tmp/key.tpl": "/etc/consul-template.d/key.tpl", "/tmp/consul-template.service": "/etc/systemd/system/consul-template.service"}

  - name: copy the nginx config file and restart nginx
    copy:
      src: /tmp/nginx.cfg
      dest: /etc/nginx/sites-available/nginx.cfg

  - name: create symlink
    file:
      src: /etc/nginx/sites-available/nginx.cfg
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: start Consul-template
    service:
      name: consul-template
      state: started

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    ignore_errors: True

  - name: Download kubernetes-client archive
    get_url:
      url: "https://dl.k8s.io/v1.13.0/kubernetes-client-linux-amd64.tar.gz"
      checksum: "sha512:61a6cd3b1fb34507e0b762a45da09d88e34921985970a2ba594e0e5af737d94c966434b4e9f8e84fb73a0aeb5fa3e557344cd2eb902bf73c67d4b4bff33c6831"
      dest: "/tmp"

  - name: Unarchive kubernetes-client
    unarchive:
      src: "/tmp/kubernetes-client-linux-amd64.tar.gz"
      dest: "/tmp"

  - name: Copy kubectl binary to destination directory
    copy:
      src: "/tmp/kubernetes/client/bin/kubectl"
      dest: "/usr/local/bin/kubectl"
      mode: 0755
      owner: root
      group: root
      remote_src: true

# Following tasks run as ssh_user instead of root
- name: Evolve Vault for demo - normal user
  hosts: 127.0.0.1
  connection: local
  any_errors_fatal: true

  tasks:
  - name: Clone Oh My Zsh! repository
    git:
      repo: https://github.com/planetrobbie/oh-my-zsh.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

  - name: Create a new zsh config from the template in the repo
    command: cp {{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template {{ ansible_env.HOME }}/.zshrc
    args:
      creates: "{{ ansible_env.HOME }}/.zshrc"

  - name: Set zsh as default shell
    user:
      name: "{{ ansible_user }}"
      shell: /usr/bin/zsh
    sudo: yes

  - name: Setup autocompletion for gcloud
    lineinfile:
      path: "{{ ansible_env.HOME }}/.zshrc"
      regexp: "completion.zsh.inc"
      line: source /usr/share/google-cloud-sdk/completion.zsh.inc

  - name: mirror fzf Pet dependency from github
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      depth: 1
      dest: ~/.fzf
      update: no

  - name: install fzf
    command: ~/.fzf/install --all

  - name: Creates Pet config directory
    file:
      path: "{{ ansible_env.HOME }}/.config/pet"
      state: directory

  - name: Clone Pet Snippets to config directory
    copy:
      remote_src: True
      src: /tmp/snippet.toml
      dest: "{{ ansible_env.HOME }}/.config/pet/"

  - name: Vault Environment Variable
    lineinfile:
      dest: "{{ ansible_env.HOME }}/.zshrc"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: 'VAULT_ADDR', line: 'export VAULT_ADDR="${vault_address}"' }
      - { regexp: 'VAULT_CACERT', line: 'export VAULT_CACERT="/etc/vault/tls/ca.crt"' }